name: on_audio_query_windows
description: The windows implementation of [on_audio_query].
version: 1.0.0
homepage: https://github.com/LucJosin/on_audio_query/tree/master/on_audio_query_windows
# pub.dev: https://pub.dev/packages/on_audio_query
# pub.dev (Windows): https://pub.dev/packages/on_audio_query_windows
# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  # on_audio_query
  on_audio_query_platform_interface:
    path: ../on_audio_query_platform_interface

  # Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    implements: on_audio_query
    platforms:
      windows:
        dartPluginClass: OnAudioQueryPlugin
