name: on_audio_query_linux
description: The linux implementation of [on_audio_query].
version: 1.0.0
homepage: https://github.com/LucJosin/on_audio_query/tree/master/on_audio_query_linux
# pub.dev: https://pub.dev/packages/on_audio_query
# pub.dev (Linux): https://pub.dev/packages/on_audio_query_linux
# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  # on_audio_query
  on_audio_query_platform_interface:
    path: ../on_audio_query_platform_interface

  # Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: OnAudioQueryLinuxPlugin